<a href="https://colab.research.google.com/github/Yewon9/BigDataCertification/blob/main/%EB%B9%85%EB%B6%84%EA%B8%B0_%EC%8B%A4%EA%B8%B0_%EC%9D%B4%EA%B8%B0%EC%A0%81.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# !pip install -r https://raw.githubusercontent.com/YoungjinBD/data/main/requirements.txt

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.7/163.7 kB 2.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 2.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.8/60.8 kB 2.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.0/63.0 kB 2.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.9/147.9 kB 8.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 167.3/167.3 kB 8.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 323.2/323.2 kB 1.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 16.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 469.0/469.0 kB 12.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 14.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 1.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 301.8/301.8 kB 10.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4

# Python 기초와 데이터 구조


## 변수와 연산

In [ ]:
# 변수에 값을 할당
number = 10
greeting = "안녕하세요!"

In [ ]:
# 변수 값을 출력
print(number)
print(greeting)

10
안녕하세요!


In [ ]:
# 변수의 타입을 변경
number = "이제 문자열입니다"
print(number)

이제 문자열입니다


In [ ]:
# 변수 할당
a = 10
b = 3.3

# 기본 산술 연산자
print("a + b =", a + b) # 덧셈
print("a - b =", a - b) # 뺄셈
print("a * b =", a * b) # 곱셈
print("a / b =", a / b) # 나눗셈
print("a % b =", a % b) # 나눗셈 연산 후 나머지를 계산
print("a // b =", a // b) # 나눗셈의 몫을 정수로 반환
print("a ** b =", a ** b) # 거듭제곱 계산

a + b = 13.3
a - b = 6.7
a * b = 33.0
a / b = 3.0303030303030303
a % b = 0.10000000000000053
a // b = 3.0
a ** b = 1995.2623149688789


In [ ]:
# 동등 비교
a = 10
b = 20
print("a == b :", a == b) # a와 b가 같은지 비교

# 부등 비교
print("a != b :", a != b) # a와 b가 다른지 비교

# 크기 비교
print("a < b :", a < b) # a가 b보다 작은지 비교
print("a > b :", a > b) # a가 b보다 큰지 비교

# 크거나 같음, 작거나 같음
print("a <= b :", a <= b) # a가 b보다 작거나 같은지 비교
print("a >= b :", a >= b) # a가 b보다 크거나 같은지 비교

a == b : False
a != b : True
a < b : True
a > b : False
a <= b : True
a >= b : False


In [ ]:
# 사용자 나이 검증 예제
user_age = 25
is_adult = user_age >= 18
print("성인입니까?", is_adult)

성인입니까? True


In [ ]:
# 논리 연산자 예제
a = True
b = False

# and 연산자
print("a and b :", a and b) # False, a와 b 둘다 참이어야 참 반환

# or 연산자
print("a or b :", a or b) # True, a와 b 중 하나라도 참이면 참 반환

# not 연산자
print("not a :", not a) # False, a와 반대 불리언 값 반환

a and b : False
a or b : True
not a : False


## 데이터 타입의 이해

In [ ]:
x = 15
print(x, "는 ", type(x), "형식이니다.", sep = '') # sep는 출력할 항목들 사이에 넣을 구분자(separator)를 지정

15는 <class 'int'>형식이니다.


In [ ]:
y = 3.14159
print(y, "는 ", type(y), "형식이니다.", sep = '')

3.14159는 <class 'float'>형식이니다.


In [ ]:
a = "Hello, world!"
b = 'python programming'

# 여러 줄 문자열
ml_str = """This is
 a multi-line
  string"""

print(a, type(a))
print(b, type(b))
print(ml_str, type(ml_str))

Hello, world! <class 'str'>
python programming <class 'str'>
This is
 a multi-line
  string <class 'str'>


In [ ]:
# 문자열 결합
greeting = "안녕" + " "  + "파이썬!"
print("결합된 문자열 :", greeting)

# 문자열 반복
laugh = "하" * 4
print("반복된 문자열 :", laugh)

결합된 문자열 : 안녕 파이썬!
반복된 문자열 : 하하하하


In [ ]:
fruits = ['apple', 'banana', 'cherry']
numbers = [1, 2, 3, 4, 5]
mixed_list = [1, "Hello", [1, 2, 3]]

print("Fruits :", fruits)
print("Numbers :", numbers)
print("Mixed List :", mixed_list)

Fruits : ['apple', 'banana', 'cherry']
Numbers : [1, 2, 3, 4, 5]
Mixed List : [1, 'Hello', [1, 2, 3]]


In [ ]:
a = [10, 20, 30, 40, 50]

# 인덱싱
print("첫 번째 요소 :", a[0]) # 10
print("마지막 요소 :", a[-1]) # 50

# 슬라이싱 (a[start:end:step])
print("처음 두 개 요소 :", a[:2]) # [10, 20]
print("중간 세 개 요소 :", a[1:4]) # [20, 30, 40]
print("모든 요소 (2개씩 건너뛰기)", a[::2]) # [10, 30, 50]

첫 번째 요소 : 10
마지막 요소 : 50
처음 두 개 요소 : [10, 20]
중간 세 개 요소 : [20, 30, 40]
모든 요소 (2개씩 건너뛰기) [10, 30, 50]


In [ ]:
fruits = ["apple", "banana"]
print("생성 시 리스트 :", fruits)

fruits[1] = "orange" # 기존 요소 변경
print("변경 된 리스트 :", fruits)

생성 시 리스트 : ['apple', 'banana']
변경 된 리스트 : ['apple', 'orange']


In [ ]:
a = (10, 20, 30) # a = 10, 20, 30과 동일
b = (42, )

print("좌표 :", a)
print("단원소 튜플 :", b)

좌표 : (10, 20, 30)
단원소 튜플 : (42,)


In [ ]:
a = (10, 20, 30)

# 인덱싱
print("첫번째 좌표 :", a[0])

# 슬라이싱
print("마지막 두 개 좌표 :", a[1:])

첫번째 좌표 : 10
마지막 두 개 좌표 : (20, 30)


In [ ]:
fruits = ("apple", "banana", "cherry")

# 튜플의 요소를 변경 시도 -> TypeError 발생
fruits[1] = "orange"
print("변경 후 튜플 :",fruits) # 실행되지 않음

TypeError: 'tuple' object does not support item assignment

In [ ]:
person = {
    'name' : 'John',
    'age' : 30,
    'city' : 'New York'
}
print("Person :", person)

Person : {'name': 'John', 'age': 30, 'city': 'New York'}


In [ ]:
print("이름 :", person['name'])
print("나이 :", person['age'])
print("도시 :", person['city'])

이름 : John
나이 : 30
도시 : New York


In [ ]:
fruits = {'apple', 'banana', 'cherry', 'apple'}
print("Fruits set :", fruits) # 중복 'apple'은 제거됨

# 빈 집합 생성
empty_set = set()
print("Empty set :", empty_set)

Fruits set : {'cherry', 'apple', 'banana'}
Empty set : set()


In [ ]:
# 요소 추가
fruits.add('orange')
print("After ading orange :", fruits)
# 요소 삭제
fruits.remove('banana')
print("After removing banana :", fruits)

After ading orange : {'cherry', 'apple', 'orange', 'banana'}
After removing banana : {'cherry', 'apple', 'orange'}


In [ ]:
# 집합 간 연산
other_fruits = {'berry', 'cherry'}
union_fruits = fruits.union(other_fruits)
intersection_fruits = fruits.intersection(other_fruits)
print("Union of fruits :", union_fruits)
print("Intersection of fruits :", intersection_fruits)

Union of fruits : {'apple', 'cherry', 'orange', 'berry'}
Intersection of fruits : {'cherry'}


In [ ]:
p = True
q = False
print(p, type(p))
print(q, type(q))
print(p + p) # True는 1로, False는 0으로 계산

True <class 'bool'>
False <class 'bool'>
2


In [ ]:
is_active = True
is_greater = 10 > 5 # True 반환
is_equal = (10 == 5) # False 반환

print("Is active :", is_active)
print("Is 10 greater than 5? :", is_greater)
print("Is 10 equal to 5? :", is_equal)

Is active : True
Is 10 greater than 5? : True
Is 10 equal to 5? : False


In [ ]:
# 논리 AND 연산
print("True and False :", True and False) # False
# 논리 OR 연산
print("True or False :", True or False) # True
# 논리 NOT 연산
print("not True :", not True) # False

True and False : False
True or False : True
not True : False


In [ ]:
a = 3
if (a == 2): # a는 3이므로 False
  print("a는 2와 같습니다.")
else:
  print("a는 2와 같지 않습니다.")

a는 2와 같지 않습니다.


In [ ]:
# 숫자형을 문자열형으로 변환
num = 123
str_num = str(num)
print("문자열 :", str_num, type(str_num))

# 문자열형을 숫자형(실수)으로 변환
num_again = float(str_num)
print("숫자형 :", num_again, type(num_again))

문자열 : 123 <class 'str'>
숫자형 : 123.0 <class 'float'>


In [ ]:
# 리스트와 튜플 변환
lst = [1, 2, 3]
print("리스트 :", lst)
tup = tuple(lst)
print("튜플 :", tup)

리스트 : [1, 2, 3]
튜플 : (1, 2, 3)


In [ ]:
set_example = {'a', 'b', 'c'}
# 딕셔너리로 변환 시, 일반적으로 집합 요소를 키 또는 값으로 사용
dict_from_set = {key: True for key in set_example}
print("Dictionary from set :", dict_from_set)

Dictionary from set : {'c': True, 'b': True, 'a': True}


In [ ]:
# 숫자를 논리형으로 변환
zero = 0
non_zero = 7
bool_from_zero = bool(zero) # False
bool_from_non_zero = bool(non_zero) # True
print("0을 논리형으로 바꾸면 :", bool_from_zero)
print("7을 논리형으로 바꾸면 :", bool_from_non_zero)

# 논리형을 숫자로 변환
true_bool = True
false_bool = False
int_from_true = int(true_bool) # 1
int_from_false = int(false_bool) # 0
print("True는 숫자로 :", int_from_true)
print("False는 숫자로 :", int_from_false)

0을 논리형으로 바꾸면 : False
7을 논리형으로 바꾸면 : True
True는 숫자로 : 1
False는 숫자로 : 0


In [ ]:
# 논리형을 문자열로 변환
str_from_true = str(true_bool) # "True"
str_from_false = str(false_bool) # "False"
print("True는 문자열로 :", str_from_true)
print("False는 문자열로 :", str_from_false)

# 문자열을 논리형으로 변환
str_true = "True"
str_false = "False"
bool_from_str_true = bool(str_true) # True
bool_from_str_false = bool(str_false) # True, 비어있지 않으면 무조건 참
print("'True'는 논리형으로 바꾸면 :", bool_from_str_true)
print("'False'는 논리형으로 바꾸면 :", bool_from_str_false)

True는 문자열로 : True
False는 문자열로 : False
'True'는 논리형으로 바꾸면 : True
'False'는 논리형으로 바꾸면 : True


## Numpy와 벡터

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5]) # 숫자형 벡터 생성
b = np.array(["apple", "banana", "orange"]) # 문자형 벡터 생성
c = np.array([True, False, True, True]) # 논리형 벡터 생성

print("Numeric Vector :", a)
print("String Vector :", b)
print("Boolean Vector :",c)

Numeric Vector : [1 2 3 4 5]
String Vector : ['apple' 'banana' 'orange']
Boolean Vector : [ True False  True  True]


In [3]:
# 빈 배열 생성
x = np.empty(3)
print("빈 벡터 생성하기 :", x) # 메모리의 임의의 값을 가지며 시스템에 따라 다름

# 배열 채우기
x[0] = 3
x[1] = 5
x[2] = 3
print("채워진 벡터 :", x)

빈 벡터 생성하기 : [2.41907520e-312 2.33419537e-312 2.14321575e-312]
채워진 벡터 : [3. 5. 3.]


In [4]:
arr1 = np.arange(10)
print("Array from 0 to 9 :", arr1)

Array from 0 to 9 : [0 1 2 3 4 5 6 7 8 9]


In [5]:
arr2 = np.arange(0, 2, 0.5)
print("0부터 2 미만까지 0.5 간격으로 발생 :", arr2)

0부터 2 미만까지 0.5 간격으로 발생 : [0.  0.5 1.  1.5]


In [6]:
linear_space1 = np.linspace(0, 1, 5)
print("0부터 1까지 5개 원소 :", linear_space1)

0부터 1까지 5개 원소 : [0.   0.25 0.5  0.75 1.  ]


In [8]:
linear_space2 = np.linspace(0, 1, 5, endpoint = False)
print("0부터 1까지 5개 원소, endpoint 제외 :", linear_space2)

0부터 1까지 5개 원소, endpoint 제외 : [0.  0.2 0.4 0.6 0.8]


In [9]:
# 숫자 8을 4번 반복
repeated_vals = np.repeat(8, 4)
print("Repeated 8 four times :", repeated_vals)

Repeated 8 four times : [8 8 8 8]


In [10]:
# 배열 [1, 2, 4]를 2번 반복
repeated_array = np.repeat([1, 2, 4], 2)
print("Repeated array [1, 2, 4] two times :", repeated_array)

Repeated array [1, 2, 4] two times : [1 1 2 2 4 4]


In [11]:
# 배열 [1, 2, 4]의 각 요소를 각각 1, 2, 3번 반복
repeated_each = np.repeat([1, 2, 4], repeats = [1, 2, 3]) # repeats 인수를 배열로 사용
print("Repeated each element in [1, 2, 4] two times :", repeated_each)

Repeated each element in [1, 2, 4] two times : [1 2 2 4 4 4]


In [12]:
# 배열 [1, 2, 4]를 2회 반복
repeated_whole = np.tile([1, 2, 4], 2)
print("벡터 전체를 두 번 반복 :", repeated_whole)

벡터 전체를 두 번 반복 : [1 2 4 1 2 4]


In [13]:
a = np.array([1, 2, 3, 4, 5]) # 1차원 배열
len(a)

5

In [14]:
a = np.array([1, 2, 3, 4, 5])
a.shape

(5,)

In [15]:
a = np.array([1, 2, 3, 4, 5])
a.size

5

In [17]:
# a를 랜덤하게 채움
np.random.seed(42) # 동일한 결과를 위한 설정
a = np.random.randint(1, 21, 10)
print(a)
print(a[1]) # 두 번째 값 추출 (0이 첫 번째)

[ 7 20 15 11  8  7 19 11 11  4]
20


In [18]:
# 세 번째부터 다섯 번째 값 추출
print(a[2:5])

[15 11  8]


In [19]:
# 첫 번째, 세 번째, 다섯 번째 값 추출
print(a[[0, 2, 4]])
# 두 번째 값 제외하고 추출
print(np.delete(a, 1))

[ 7 15  8]
[ 7 15 11  8  7 19 11 11  4]


In [20]:
# 인덱싱 중복 선택
print(a)
print(a[[1, 1, 3, 2]])

[ 7 20 15 11  8  7 19 11 11  4]
[20 20 11 15]


In [21]:
b = a[a > 3]
print(b)

[ 7 20 15 11  8  7 19 11 11  4]


In [22]:
b = a[(a > 2) & (a < 9)]
print(b)

[7 8 7 4]


In [23]:
print(a[a == 8])
print(a[a != 8])

[8]
[ 7 20 15 11  7 19 11 11  4]


In [24]:
print(~(a == 8))
print(a[~(a == 8)])

[ True  True  True  True False  True  True  True  True  True]
[ 7 20 15 11  7 19 11 11  4]


In [25]:
b = a[np.arange(1, 11) % 2 == 1]
print(b)

[ 7 15  8 19 11]


In [26]:
b = a[a% 3 == 0]
print(b)

[15]


In [27]:
x = np.array([True, True, False])
y = np.array([True, False, False])
print(x & y)

[ True False False]


In [28]:
print(x | y)

[ True  True False]


In [29]:
a = np.array([1, 2, 3, 4, 16, 17, 18]) # 예시 배열

result = a[(a == 4) & (a > 15)]
print(result)

[]


In [30]:
result = a[(a == 4) | (a > 15)]
print(result)

[ 4 16 17 18]


In [31]:
a = np.array([5, 10, 15, 20, 25, 30])

a[a >= 10] = 10
a

array([ 5, 10, 10, 10, 10, 10])

In [32]:
a = np.array([1, 5, 7, 8, 10]) # 예시 배열

result = a < 7
result

array([ True,  True, False, False, False])

In [33]:
result = np.where(a < 7)
result

(array([0, 1]),)

In [34]:
a = np.array([1, 2, 3, 4, 5])

sum_a = np.sum(a) # 합계 계산
mean_a = np.mean(a) # 평균 계산
median_a = np.median(a) # 중앙값 계산
std_a = np.std(a, ddof = 1) # 표준편차 계산

sum_a, mean_a, median_a, std_a

(np.int64(15),
 np.float64(3.0),
 np.float64(3.0),
 np.float64(1.5811388300841898))

In [35]:
a = np.array([20, np.nan, 13, 24, 309])
a

array([ 20.,  nan,  13.,  24., 309.])

In [36]:
np.mean(a)

np.float64(nan)

In [38]:
np.nanmean(a) # nan 무시 함수

np.float64(91.5)

In [39]:
value = np.nan
if np.isnan(value):
  print("값이 NaN입니다.")

값이 NaN입니다.


In [40]:
value + 1 # 수치연산이 가능하나 결과는 nan

nan

In [41]:
my_variable = None
if my_variable is None:
  print("변수에 값이 없습니다.")

변수에 값이 없습니다.


In [42]:
None + 1 # 수치연산 불가

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

In [43]:
a = np.array([20, np.nan, 13, 24, 309])

a_filtered = a[~np.isnan(a)]
a_filtered

array([ 20.,  13.,  24., 309.])

In [44]:
str_vec = np.array(["사과", "배", "수박", "참외"])
str_vec # dtype에서 U2는 최대 2글자의 유니코드 문자열이라는 의미

array(['사과', '배', '수박', '참외'], dtype='<U2')

In [46]:
mix_vec = np.array(["사과", 12, "수박", "참외"], dtype = str)
mix_vec

array(['사과', '12', '수박', '참외'], dtype='<U2')

In [47]:
combined_vec = np.concatenate((str_vec, mix_vec))
combined_vec

array(['사과', '배', '수박', '참외', '사과', '12', '수박', '참외'], dtype='<U2')

In [48]:
col_stacked = np.column_stack((np.arange(1, 5), np.arange(12, 16)))
col_stacked

array([[ 1, 12],
       [ 2, 13],
       [ 3, 14],
       [ 4, 15]])

In [49]:
row_stacked = np.row_stack((np.arange(1, 5), np.arange(12, 16)))
row_stacked

<ipython-input-49-f49bbfa55f45>:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  row_stacked = np.row_stack((np.arange(1, 5), np.arange(12, 16)))


array([[ 1,  2,  3,  4],
       [12, 13, 14, 15]])

In [50]:
uneven_stacked = np.column_stack((np.arange(1, 5), np.arange(12, 18)))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 6

In [51]:
vec1 = np.arange(1, 5)
vec2 = np.arange(12, 18)
vec1 = np.resize(vec1, len(vec2))
vec1

array([1, 2, 3, 4, 1, 2])

In [52]:
uneven_stacked = np.column_stack((vec1, vec2))
uneven_stacked

array([[ 1, 12],
       [ 2, 13],
       [ 3, 14],
       [ 4, 15],
       [ 1, 16],
       [ 2, 17]])

### 연습문제

In [53]:
# 1. 주어진 벡터의 각 요소에 5를 더한 새로운 벡터를 생성하시오.
a = np.array([1, 2, 3, 4, 5])
b = a + 5
b

array([ 6,  7,  8,  9, 10])

In [54]:
# 2. 주어진 벡터의 홀수 번째 요소만 추출하여 새로운 백터를 생성하시오.
a = np.array([12, 21, 35, 48, 5])
b = a[::2]
b

array([12, 35,  5])

In [60]:
# 3. 주어진 벡터에서 최댓값을 찾으시오.
a = np.array([1, 22, 93, 64, 54])
np.max(a)

np.int64(93)

In [61]:
# 4. 주어진 벡터에서 중복된 값을 제거한 새로운 벡터를 생성하시오.
a = np.array([1, 2, 3, 2, 4, 5, 4, 6])
np.unique(a)

array([1, 2, 3, 4, 5, 6])

In [63]:
# 5. 주어진 두 벡터 a, b의 요소를 번갈아 가면서 위치시키는 새로운 벡터를 생성하시오.
a = np.array([21, 31, 58])
b = np.array([24, 44, 67])
c = np.empty(a.size + b.size, dtype = a.dtype)
c[0::2] = a
c[1::2] = b
print(c)

[21 24 31 44 58 67]


In [64]:
# 6. 다음 두 벡터 a와 b를 더한 결과를 구하시오. (벡터 a의 마지막 값은 제외)
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9])
c = a[:-1] + b
print(c)

[ 7  9 11 13]
